import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SocietySummaryReportData, IncomeEntry, ExpenseEntry, Member } from '../types';
import {
  computeProjectFinancials,
  computeDirectorSummaries,
  computeAllMemberSummaries,
  formatBDT,
} from './calculations';
import { TOTAL_SHARES } from './directors';
import { storageService } from '../services/storageService';

/**
 * Generates an executive-grade summary PDF report for the entire society,
 * aggregating annual income, expenses, budget variance, and 144-share ledger health,
 * suitable for official board presentation and audit archives.
 */
export function generateSocietySummaryPDF(data: SocietySummaryReportData): jsPDF {
  const {
    fiscalYear = '2025-2026',
    incomes,
    expenses,
    members,
    currentUser,
    reportDate = new Date().toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    }),
  } = data;

  // Initialize jsPDF document (Portrait, A4 format)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  // 1. Calculate Aggregate Financials
  const financials = computeProjectFinancials(incomes, expenses);
  const directorSummaries = computeDirectorSummaries(incomes, expenses);
  const memberSummaries = computeAllMemberSummaries(members, incomes, expenses);
  const varianceReport = storageService.computeBudgetVarianceReport(fiscalYear);

  // Share ledger health metrics
  const advanceMembers = memberSummaries.filter((m) => m.currentBalance > 0.01);
  const overdueMembers = memberSummaries.filter((m) => m.currentBalance < -0.01);
  const balancedMembers = memberSummaries.filter(
    (m) => Math.abs(m.currentBalance) <= 0.01
  );

  const totalOverdueReceivable = overdueMembers.reduce(
    (sum, m) => sum + Math.abs(m.currentBalance),
    0
  );
  const totalAdvanceSurplus = advanceMembers.reduce(
    (sum, m) => sum + m.currentBalance,
    0
  );
  const collectionComplianceRate =
    TOTAL_SHARES > 0
      ? ((advanceMembers.length + balancedMembers.length) / TOTAL_SHARES) * 100
      : 0;

  // Incomes by Category
  const incomeCategoryMap: Record<string, { count: number; total: number }> = {};
  incomes
    .filter((i) => i.status === 'APPROVED' && !i.isSoftDeleted)
    .forEach((inc) => {
      const cat = inc.category || 'General Capital Deposit';
      if (!incomeCategoryMap[cat]) incomeCategoryMap[cat] = { count: 0, total: 0 };
      incomeCategoryMap[cat].count++;
      incomeCategoryMap[cat].total += inc.amount;
    });

  // Expenses by Category
  const expenseCategoryMap: Record<string, { count: number; total: number }> = {};
  expenses
    .filter((e) => e.status === 'APPROVED' && !e.isSoftDeleted)
    .forEach((exp) => {
      const cat = exp.category || 'Site Operations';
      if (!expenseCategoryMap[cat]) expenseCategoryMap[cat] = { count: 0, total: 0 };
      expenseCategoryMap[cat].count++;
      expenseCategoryMap[cat].total += exp.amount;
    });

  // --- Header & Letterhead Function ---
  const renderHeader = (pageTitle: string, pageSubTitle: string) => {
    // Top Brand Bar (Emerald Accent)
    doc.setFillColor(16, 185, 129); // #10b981
    doc.rect(0, 0, pageWidth, 5, 'F');

    // Society Letterhead
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42); // #0f172a
    doc.text('PROTTASHA HOUSING SOCIETY LTD.', margin, 15);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105); // #475569
    doc.text('Central Directorate of Accounts, Share Allocation & Governance', margin, 20);
    doc.text('Sector 14, Uttara Model Town, Dhaka-1230, Bangladesh | 144 Share Collective Registry', margin, 24);

    // Presentation Badge / Meta
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(16, 185, 129);
    doc.text('EXECUTIVE BOARD PRESENTATION', pageWidth - margin, 14, { align: 'right' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Fiscal Year: ${fiscalYear}`, pageWidth - margin, 19, { align: 'right' });
    doc.text(`Report Date: ${reportDate}`, pageWidth - margin, 23, { align: 'right' });
    doc.text(`Generated By: ${currentUser ? currentUser.name : 'Saif Ahmed Sakil (Admin)'}`, pageWidth - margin, 27, { align: 'right' });

    // Divider Line
    doc.setDrawColor(203, 213, 225); // #cbd5e1
    doc.setLineWidth(0.6);
    doc.line(margin, 31, pageWidth - margin, 31);

    // Section Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text(pageTitle, margin, 38);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    doc.text(pageSubTitle, margin, 42);
  };

  // --- Footer Function ---
  const renderFooter = (pageNum: number, totalPages: number) => {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.4);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text('Confidential • For Board of Directors & General Assembly Review Only • Prottasha Housing Society Ltd.', margin, pageHeight - 7);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, pageHeight - 7, { align: 'right' });
  };

  // ==========================================
  // PAGE 1: EXECUTIVE SUMMARY & FINANCIAL KPIS
  // ==========================================
  renderHeader(
    'ANNUAL FINANCIAL SUMMARY & MACRO INDICATORS',
    `Comprehensive financial aggregation and treasury health audit for FY ${fiscalYear}`
  );

  let startY = 48;

  // KPI Highlights Box Grid (2x2 grid)
  const boxWidth = (pageWidth - margin * 2 - 6) / 2;
  const boxHeight = 22;

  // Box 1: Total Collections
  doc.setFillColor(240, 253, 244); // light emerald
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(margin, startY, boxWidth, boxHeight, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(22, 101, 52);
  doc.text('TOTAL REVENUE & MEMBER COLLECTIONS (JOMA)', margin + 4, startY + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 118, 110);
  doc.text(formatBDT(financials.totalCollection), margin + 4, startY + 13.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(`General: ${formatBDT(financials.totalGeneralDeposits)} | Sales: ${formatBDT(financials.totalSalesDeposits)}`, margin + 4, startY + 18.5);

  // Box 2: Total Project Expenditure
  const col2X = margin + boxWidth + 6;
  doc.setFillColor(254, 242, 242); // light rose
  doc.setDrawColor(254, 202, 202);
  doc.roundedRect(col2X, startY, boxWidth, boxHeight, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(153, 27, 27);
  doc.text('TOTAL PROJECT EXPENDITURES (KHORCH)', col2X + 4, startY + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(185, 28, 28);
  doc.text(formatBDT(financials.totalProjectExpense), col2X + 4, startY + 13.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(`Approved Vouchers: ${expenses.filter((e) => e.status === 'APPROVED').length} | Verified Audit Trail`, col2X + 4, startY + 18.5);

  // Box 3: Net Treasury Balance
  startY += boxHeight + 4;
  const isSurplus = financials.netSocietyBalance >= 0;
  if (isSurplus) {
    doc.setFillColor(240, 249, 255); // sky light
    doc.setDrawColor(186, 230, 253);
    doc.roundedRect(margin, startY, boxWidth, boxHeight, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(3, 105, 161);
  } else {
    doc.setFillColor(255, 241, 242); // light red
    doc.setDrawColor(254, 205, 211);
    doc.roundedRect(margin, startY, boxWidth, boxHeight, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(190, 18, 60);
  }
  doc.text('NET SOCIETY TREASURY BALANCE (SURPLUS/DEFICIT)', margin + 4, startY + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  if (isSurplus) {
    doc.setTextColor(14, 116, 144);
  } else {
    doc.setTextColor(225, 29, 72);
  }
  doc.text(formatBDT(financials.netSocietyBalance), margin + 4, startY + 13.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(`Liquid Capital Reserve Status: ${isSurplus ? 'Solvent & Surplus' : 'Deficit / Calls Required'}`, margin + 4, startY + 18.5);

  // Box 4: Per Share Quota & Ledger Health
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(col2X, startY, boxWidth, boxHeight, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(51, 65, 85);
  doc.text('SHARE EXPENSE QUOTA (1/144th PRO-RATA ALLOCATION)', col2X + 4, startY + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text(formatBDT(financials.perShareExpense), col2X + 4, startY + 13.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(`Compliance Rate: ${collectionComplianceRate.toFixed(1)}% (${advanceMembers.length + balancedMembers.length}/144 in Good Standing)`, col2X + 4, startY + 18.5);

  startY += boxHeight + 8;

  // Annual Budget vs Actual Expenditure Variance Summary Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(30, 41, 59);
  doc.text('1. ANNUAL BUDGET TARGETS VS ACTUAL EXPENDITURES (VARIANCE AUDIT)', margin, startY);

  const budgetTableBody = varianceReport.items.map((item) => [
    item.category,
    formatBDT(item.targetAmountBDT),
    formatBDT(item.actualExpenseBDT),
    `${item.varianceBDT >= 0 ? '+' : ''}${formatBDT(item.varianceBDT)}`,
    `${item.utilizationRate.toFixed(1)}%`,
    item.status.replace('_', ' '),
  ]);

  // Append total row
  budgetTableBody.push([
    'TOTAL BUDGET CONSOLIDATION',
    formatBDT(varianceReport.totalBudgetTargetBDT),
    formatBDT(varianceReport.totalActualExpenseBDT),
    `${varianceReport.netVarianceBDT >= 0 ? '+' : ''}${formatBDT(varianceReport.netVarianceBDT)}`,
    `${varianceReport.overallUtilizationRate.toFixed(1)}%`,
    varianceReport.netVarianceBDT >= 0 ? 'FAVORABLE SURPLUS' : 'OVER BUDGET',
  ]);

  autoTable(doc, {
    startY: startY + 2.5,
    margin: { left: margin, right: margin },
    head: [['Expense Category', 'Annual Target (BDT)', 'Actual Spent (BDT)', 'Variance (BDT)', 'Utilization', 'Budget Status']],
    body: budgetTableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // slate-800
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right', fontStyle: 'bold' },
      4: { halign: 'center' },
      5: { halign: 'center', fontStyle: 'bold' },
    },
  });

  // Annual Income Breakdown by Category
  const finalBudgetY = (doc as any).lastAutoTable.finalY + 7;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(30, 41, 59);
  doc.text('2. ANNUAL REVENUE & DEPOSIT CATEGORY AGGREGATION', margin, finalBudgetY);

  const incomeTableBody = Object.entries(incomeCategoryMap).map(([category, stats]) => {
    const percentage = financials.totalCollection > 0 ? (stats.total / financials.totalCollection) * 100 : 0;
    return [
      category,
      stats.count.toString(),
      formatBDT(stats.total),
      `${percentage.toFixed(1)}%`,
      'Approved & Deposited in Escrow',
    ];
  });

  incomeTableBody.push([
    'CONSOLIDATED REVENUE TOTAL',
    incomes.filter((i) => i.status === 'APPROVED').length.toString(),
    formatBDT(financials.totalCollection),
    '100.0%',
    'Verified Collective Capital',
  ]);

  autoTable(doc, {
    startY: finalBudgetY + 2.5,
    margin: { left: margin, right: margin },
    head: [['Deposit Category', 'Transaction Count', 'Total Credited (BDT)', 'Revenue Share %', 'Verification Audit Status']],
    body: incomeTableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [16, 149, 107], // emerald
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [240, 253, 244],
    },
    columnStyles: {
      0: { cellWidth: 55 },
      1: { halign: 'center' },
      2: { halign: 'right', fontStyle: 'bold' },
      3: { halign: 'center' },
      4: { halign: 'left' },
    },
  });

  // ==========================================
  // PAGE 2: SHARE LEDGER HEALTH & DIRECTOR PORTFOLIOS
  // ==========================================
  doc.addPage();
  renderHeader(
    'SHARE LEDGER HEALTH & DIRECTOR PORTFOLIO ANALYSIS',
    'Assessment of 144 authorized shares, compliance matrix, and director-wise collections'
  );

  let page2Y = 48;

  // Share Ledger Health Summary Cards (3 cards)
  const cardWidth = (pageWidth - margin * 2 - 8) / 3;
  const cardHeight = 22;

  // Card 1: Shareholders in Surplus / Advance
  doc.setFillColor(240, 253, 244);
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(margin, page2Y, cardWidth, cardHeight, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(22, 101, 52);
  doc.text('ADVANCE / SURPLUS SHAREHOLDERS', margin + 3.5, page2Y + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(21, 128, 61);
  doc.text(`${advanceMembers.length} Shares (${((advanceMembers.length / 144) * 100).toFixed(1)}%)`, margin + 3.5, page2Y + 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Surplus Capital: ${formatBDT(totalAdvanceSurplus)}`, margin + 3.5, page2Y + 18);

  // Card 2: Shareholders with Overdue Deficits
  const card2X = margin + cardWidth + 4;
  doc.setFillColor(254, 242, 242);
  doc.setDrawColor(254, 202, 202);
  doc.roundedRect(card2X, page2Y, cardWidth, cardHeight, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(153, 27, 27);
  doc.text('OVERDUE / PENDING DUES SHAREHOLDERS', card2X + 3.5, page2Y + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(185, 28, 28);
  doc.text(`${overdueMembers.length} Shares (${((overdueMembers.length / 144) * 100).toFixed(1)}%)`, card2X + 3.5, page2Y + 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Overdue Receivable: ${formatBDT(totalOverdueReceivable)}`, card2X + 3.5, page2Y + 18);

  // Card 3: Equilibrium & Full Compliance Rate
  const card3X = card2X + cardWidth + 4;
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(card3X, page2Y, cardWidth, cardHeight, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(30, 41, 59);
  doc.text('PORTFOLIO EQUILIBRIUM HEALTH', card3X + 3.5, page2Y + 5.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(`${collectionComplianceRate.toFixed(1)}% Healthy`, card3X + 3.5, page2Y + 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`${balancedMembers.length} Balanced | ${TOTAL_SHARES} Total Allocated Shares`, card3X + 3.5, page2Y + 18);

  page2Y += cardHeight + 8;

  // Director-Wise Controlling Portfolio Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(30, 41, 59);
  doc.text('3. DIRECTOR-WISE CONTROLLING SHARE & FINANCIAL PORTFOLIO AUDIT', margin, page2Y);

  const directorTableBody = directorSummaries.map((ds) => [
    ds.director.name,
    `${ds.director.shareCount} Shares (#${ds.director.startShare}-${ds.director.endShare})`,
    formatBDT(ds.totalCollection),
    formatBDT(ds.totalExpense),
    `${ds.currentBalance >= 0 ? '+' : ''}${formatBDT(ds.currentBalance)}`,
    `${ds.collectionPercentage.toFixed(1)}%`,
    ds.status,
  ]);

  autoTable(doc, {
    startY: page2Y + 2.5,
    margin: { left: margin, right: margin },
    head: [['Controlling Director', 'Share Block Range', 'Total Collection (BDT)', 'Quota Khorch (BDT)', 'Net Balance (BDT)', 'Recovery %', 'Status']],
    body: directorTableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 46 },
      1: { cellWidth: 32 },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right', fontStyle: 'bold' },
      5: { halign: 'center' },
      6: { halign: 'center', fontStyle: 'bold' },
    },
  });

  // Top Overdue Accounts Requiring Board Notice
  const finalDirY = (doc as any).lastAutoTable.finalY + 7;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(185, 28, 28);
  doc.text(`4. OVERDUE SHARE ACCOUNTS REQUIRING IMMEDIATE BOARD INTERVENTION (${overdueMembers.length} ACCOUNTS)`, margin, finalDirY);

  const topOverdueAccounts = overdueMembers
    .sort((a, b) => a.currentBalance - b.currentBalance)
    .slice(0, 10);

  const overdueTableBody = topOverdueAccounts.map((om) => [
    om.memberId,
    om.member.name,
    `Share #${om.shareNumber}`,
    om.controllingDirector.name,
    formatBDT(om.memberPersonalDeposit),
    formatBDT(om.memberShareExpense),
    formatBDT(Math.abs(om.currentBalance)),
    'Demand Notice Active',
  ]);

  if (overdueTableBody.length === 0) {
    overdueTableBody.push([
      'N/A',
      'All 144 Shareholder accounts are in full equilibrium and advance standing.',
      '—',
      '—',
      '—',
      '—',
      'BDT 0',
      'OPTIMAL',
    ]);
  }

  autoTable(doc, {
    startY: finalDirY + 2.5,
    margin: { left: margin, right: margin },
    head: [['Member ID', 'Shareholder Name', 'Share #', 'Controlling Director', 'Deposited (BDT)', 'Quota (BDT)', 'Overdue Deficit (BDT)', 'Action Status']],
    body: overdueTableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [185, 28, 28], // red-700
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [254, 242, 242],
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 38 },
      2: { halign: 'center' },
      3: { cellWidth: 32 },
      4: { halign: 'right' },
      5: { halign: 'right' },
      6: { halign: 'right', fontStyle: 'bold', textColor: [185, 28, 28] },
      7: { halign: 'center' },
    },
  });

  // ==========================================
  // PAGE 3: BOARD RESOLUTIONS & FORMAL SIGN-OFFS
  // ==========================================
  doc.addPage();
  renderHeader(
    'EXECUTIVE BOARD RESOLUTIONS & OFFICIAL CERTIFICATION',
    'Formal recommendations, statutory compliances, and executive director signatures'
  );

  let page3Y = 48;

  // Board Recommendations Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, page3Y, pageWidth - margin * 2, 70, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('STATUTORY BOARD FINDINGS & RECOMMENDED EXECUTIVE ACTIONS:', margin + 5, page3Y + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);

  const recommendations = [
    `1. Liquidity & Capital Preservation: The society holds a net treasury position of ${formatBDT(financials.netSocietyBalance)}. Ongoing infrastructure contracts (earth filling, culvert construction, boundary security) should proceed under audited stage-gate disbursements.`,
    `2. Overdue Share Capital Recovery: A total of ${formatBDT(totalOverdueReceivable)} remains overdue across ${overdueMembers.length} shareholder accounts. Automated demand notices issued via the InfoCommunication portal must be strictly monitored with a 15-day settlement deadline.`,
    `3. Controlling Director Follow-up: Directors with portfolios in deficit must coordinate direct shareholder outreach for pending share call payments to prevent construction delays in Phase-1 Sector 14.`,
    `4. Annual Budget Discipline: Actual expenditures remain tracked against the FY ${fiscalYear} budget target of ${formatBDT(varianceReport.totalBudgetTargetBDT)}. Procurement variations over 10% must receive advance Executive Committee sanction.`,
    `5. Share Ledger Demographics & Certification: All 144 registered shares remain verified and mapped to official National ID, phone, email, and designated plot layouts in the society central registry.`,
  ];

  let recY = page3Y + 14;
  recommendations.forEach((rec) => {
    const lines = doc.splitTextToSize(rec, pageWidth - margin * 2 - 10);
    doc.text(lines, margin + 5, recY);
    recY += lines.length * 4.2 + 2;
  });

  // Official Board Signatures & Stamp Block
  page3Y += 85;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(30, 41, 59);
  doc.text('OFFICIAL EXECUTIVE COMMITTEE CERTIFICATION & SIGNATURES', margin, page3Y);

  const sigColWidth = (pageWidth - margin * 2 - 12) / 3;
  const sigBoxY = page3Y + 8;

  // Signature 1: President & Root System Admin
  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(margin, sigBoxY + 20, margin + sigColWidth, sigBoxY + 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text('Saif Ahmed Sakil', margin, sigBoxY + 25);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('President & Root System Admin', margin, sigBoxY + 29);
  doc.text('ISRT, University of Dhaka', margin, sigBoxY + 33);
  doc.text('Prottasha Housing Society Ltd.', margin, sigBoxY + 37);

  // Signature 2: Director - Technical & Planning
  const sig2X = margin + sigColWidth + 6;
  doc.line(sig2X, sigBoxY + 20, sig2X + sigColWidth, sigBoxY + 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text('Engr. Rashedul Islam', sig2X, sigBoxY + 25);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Director - Technical & Planning', sig2X, sigBoxY + 29);
  doc.text('Executive Committee Member', sig2X, sigBoxY + 33);
  doc.text('Prottasha Housing Society Ltd.', sig2X, sigBoxY + 37);

  // Signature 3: Director - Finance & Audit
  const sig3X = sig2X + sigColWidth + 6;
  doc.line(sig3X, sigBoxY + 20, sig3X + sigColWidth, sigBoxY + 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text('Dr. Farhana Chowdhury', sig3X, sigBoxY + 25);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Director - Finance & Internal Audit', sig3X, sigBoxY + 29);
  doc.text('Executive Committee Member', sig3X, sigBoxY + 33);
  doc.text('Prottasha Housing Society Ltd.', sig3X, sigBoxY + 37);

  // Official Escrow Seal Stamp Box
  const sealY = sigBoxY + 48;
  doc.setFillColor(241, 245, 249);
  doc.setDrawColor(148, 163, 184);
  doc.roundedRect(margin, sealY, pageWidth - margin * 2, 28, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(30, 41, 59);
  doc.text('OFFICIAL REGISTRATION SEAL & AUDIT TIMESTAMP HASH:', margin + 4, sealY + 6);

  doc.setFont('courier', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  const hashString = `SHA256:${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substring(2, 10).toUpperCase()}-144SHARES-PHS-AUDIT-FY${fiscalYear}`;
  doc.text(`Digital Escrow Signature: ${hashString}`, margin + 4, sealY + 12);
  doc.text(`Certified under Society Registration Act & Prottasha Housing Society Governance Bylaws 2026.`, margin + 4, sealY + 17);
  doc.text(`Registry Address: Sector 14, Uttara, Dhaka | Verified by System Admin Sakil (Applied Statistics, DU)`, margin + 4, sealY + 22);

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    renderFooter(p, totalPages);
  }

  return doc;
}

/**
 * Convenience helper to generate and trigger instant download of the Society Summary PDF report.
 */
export function downloadSocietySummaryPDF(data: SocietySummaryReportData, filename?: string): void {
  const doc = generateSocietySummaryPDF(data);
  const dateStr = new Date().toISOString().split('T')[0];
  const fiscalYearClean = (data.fiscalYear || '2025-2026').replace(/\s+/g, '_');
  const actualFilename =
    filename || `PHS_Board_Executive_Summary_Report_FY_${fiscalYearClean}_${dateStr}.pdf`;

  doc.save(actualFilename);
}
