import {
  IncomeEntry,
  ExpenseEntry,
  AuditLog,
  ChatMessage,
  ElectionPoll,
  ExecutiveCommittee,
  OfficialUser,
  PromotedECMember,
  SocietyDocument,
  MemberQuery,
  DiscussionPost,
} from '../types';
import { generateInitialMembers, DIRECTORS } from './directors';

export const INITIAL_MEMBERS = generateInitialMembers();

export const INITIAL_OFFICIALS: OfficialUser[] = [
  {
    id: 'OFF-001',
    username: 'manager1',
    name: 'Md. Rafiqul Islam',
    designation: 'Manager',
    phone: '+8801711998877',
    email: 'rafiqul.manager@prottasha.org',
    department: 'Accounts & Operations',
    isEmpoweredForEntry: true, // Empowered by System Admin
    empoweredBy: 'Saif Ahmed Sakil (System Admin)',
    empoweredAt: '2026-01-10T10:00:00.000Z',
    createdAt: '2026-01-10T10:00:00.000Z',
    createdBy: 'Saif Ahmed Sakil',
    status: 'ACTIVE',
  },
  {
    id: 'OFF-002',
    username: 'dym_hasan',
    name: 'Kazi Hasan',
    designation: 'Deputy Manager (DyM)',
    phone: '+8801711883322',
    email: 'hasan.dym@prottasha.org',
    department: 'Field Operations & Billing',
    isEmpoweredForEntry: true, // Empowered by System Admin
    empoweredBy: 'Saif Ahmed Sakil (System Admin)',
    empoweredAt: '2026-01-15T11:00:00.000Z',
    createdAt: '2026-01-15T11:00:00.000Z',
    createdBy: 'Saif Ahmed Sakil',
    status: 'ACTIVE',
  },
  {
    id: 'OFF-003',
    username: 'aistm_kamal',
    name: 'Kamal Hossain',
    designation: 'Assistant Manager (AistM)',
    phone: '+8801711774433',
    email: 'kamal.aistm@prottasha.org',
    department: 'Member Liaison & Desk',
    isEmpoweredForEntry: false, // NOT empowered by System Admin yet
    createdAt: '2026-02-01T09:00:00.000Z',
    createdBy: 'Saif Ahmed Sakil',
    status: 'ACTIVE',
  },
  {
    id: 'OFF-004',
    username: 'accts_tanvir',
    name: 'Tanvir Chowdhury',
    designation: 'Accounts Officer',
    phone: '+8801711665544',
    email: 'tanvir.accounts@prottasha.org',
    department: 'Finance & Banking Escrow',
    isEmpoweredForEntry: true, // Empowered by System Admin
    empoweredBy: 'Saif Ahmed Sakil (System Admin)',
    empoweredAt: '2026-02-05T14:00:00.000Z',
    createdAt: '2026-02-05T14:00:00.000Z',
    createdBy: 'Saif Ahmed Sakil',
    status: 'ACTIVE',
  },
];

export const INITIAL_EXECUTIVE_COMMITTEE: ExecutiveCommittee = {
  president: {
    name: 'Saif Ahmed Sakil',
    memberId: 'PHSM-001',
    honorariumBDT: 35000,
    phone: '+8801611447765',
    designation: 'President',
  },
  vicePresident: {
    name: 'M Omar Faruque Molla',
    memberId: 'PHSM-049',
    honorariumBDT: 25000,
    phone: '+8801811334455',
    designation: 'VICE PRESIDENT (VP)',
  },
  generalSecretary: {
    name: 'M Masud Sawdagor',
    memberId: 'PHSM-021',
    honorariumBDT: 30000,
    phone: '+8801711223344',
    designation: 'General Secretary',
  },
  treasurer: {
    name: 'Sirajul Islam',
    memberId: 'PHSM-088',
    honorariumBDT: 25000,
    phone: '+8801611667788',
    designation: 'TREASURER',
  },
  additionalECMembers: [
    {
      id: 'EC-ADD-01',
      memberId: 'PHSM-056',
      name: 'Shahin Ahmed',
      designation: 'MEMBER',
      honorariumBDT: 20000,
      phone: '+8801911445566',
      appointedAt: '2026-01-10T10:00:00.000Z',
      appointedBy: 'Saif Ahmed Sakil (System Admin)',
    },
    {
      id: 'EC-ADD-02',
      memberId: 'PHSM-071',
      name: 'Abul Hashim',
      designation: 'MEMBER',
      honorariumBDT: 20000,
      phone: '+8801511556677',
      appointedAt: '2026-01-10T10:00:00.000Z',
      appointedBy: 'Saif Ahmed Sakil (System Admin)',
    },
    {
      id: 'EC-ADD-03',
      memberId: 'PHSM-095',
      name: 'M Abu Yousuf',
      designation: 'MEMBER',
      honorariumBDT: 20000,
      phone: '+8801711778899',
      appointedAt: '2026-01-10T10:00:00.000Z',
      appointedBy: 'Saif Ahmed Sakil (System Admin)',
    },
    {
      id: 'EC-ADD-04',
      memberId: 'PHSM-102',
      name: 'Faizan Ahmed',
      designation: 'MEMBER',
      honorariumBDT: 20000,
      phone: '+8801811889900',
      appointedAt: '2026-01-10T10:00:00.000Z',
      appointedBy: 'Saif Ahmed Sakil (System Admin)',
    },
  ],
  termYear: '2025-2027',
  lastUpdated: '2026-01-10T10:00:00.000Z',
};

export const INITIAL_INCOMES: IncomeEntry[] = [
  // General Member Deposits
  {
    id: 'DEP-2026-001',
    type: 'GENERAL_DEPOSIT',
    amount: 150000,
    category: 'Development Fee - Phase 1',
    date: '2026-01-12',
    shareOwnerId: 'PHSM-001',
    memberName: 'Saif Ahmed Sakil',
    controllingDirector: 'SAIF AHMED SAKIL',
    shareNumber: 1,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'DBBL-TRX-994821',
    remarks: 'Phase 1 boundary wall development share deposit',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-01-12T14:30:00.000Z',
    createdAt: '2026-01-12T11:00:00.000Z',
    updatedAt: '2026-01-12T14:30:00.000Z',
  },
  {
    id: 'DEP-2026-002',
    type: 'GENERAL_DEPOSIT',
    amount: 180000,
    category: 'Member Monthly Contribution',
    date: '2026-01-15',
    shareOwnerId: 'PHSM-021',
    memberName: 'M Masud Sawdagor',
    controllingDirector: 'M MASUD SAWDAGOR',
    shareNumber: 21,
    paymentMethod: 'Cheque',
    referenceNumber: 'IBBL-CHQ-481902',
    remarks: 'Q1 Land filing and road leveling advance',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-01-16T09:15:00.000Z',
    createdAt: '2026-01-15T15:20:00.000Z',
    updatedAt: '2026-01-16T09:15:00.000Z',
  },
  {
    id: 'DEP-2026-003',
    type: 'GENERAL_DEPOSIT',
    amount: 120000,
    category: 'Development Fee - Phase 1',
    date: '2026-01-18',
    shareOwnerId: 'PHSM-049',
    memberName: 'M Omar Faruque Molla',
    controllingDirector: 'M OMAR FARUQUE MOLLA',
    shareNumber: 49,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'SCB-FT-883719',
    remarks: 'Drainage line contribution',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-del-1',
    approvedByName: 'M Masud Sawdagor',
    approvedAt: '2026-01-19T10:00:00.000Z',
    createdAt: '2026-01-18T16:00:00.000Z',
    updatedAt: '2026-01-19T10:00:00.000Z',
  },
  {
    id: 'DEP-2026-004',
    type: 'GENERAL_DEPOSIT',
    amount: 140000,
    category: 'Development Fee - Phase 1',
    date: '2026-01-22',
    shareOwnerId: 'PHSM-056',
    memberName: 'Shahin Ahmed',
    controllingDirector: 'SHAHIN AHMED',
    shareNumber: 56,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'EBL-TRX-204918',
    remarks: 'Sector 14 earth filing payment',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-01-22T18:00:00.000Z',
    createdAt: '2026-01-22T12:00:00.000Z',
    updatedAt: '2026-01-22T18:00:00.000Z',
  },
  {
    id: 'DEP-2026-005',
    type: 'GENERAL_DEPOSIT',
    amount: 150000,
    category: 'Development Fee - Phase 1',
    date: '2026-01-25',
    shareOwnerId: 'PHSM-071',
    memberName: 'Abul Hashim',
    controllingDirector: 'ABUL HASHIM',
    shareNumber: 71,
    paymentMethod: 'Cheque',
    referenceNumber: 'PBL-CHQ-119283',
    remarks: 'Main gate and security post construction share',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-01-26T11:45:00.000Z',
    createdAt: '2026-01-25T14:10:00.000Z',
    updatedAt: '2026-01-26T11:45:00.000Z',
  },
  {
    id: 'DEP-2026-006',
    type: 'GENERAL_DEPOSIT',
    amount: 110000,
    category: 'Development Fee - Phase 1',
    date: '2026-02-01',
    shareOwnerId: 'PHSM-088',
    memberName: 'Sirajul Islam',
    controllingDirector: 'SIRAJUL ISLAM',
    shareNumber: 88,
    paymentMethod: 'Cash',
    referenceNumber: 'CASH-RCT-0042',
    remarks: 'Cash deposit deposited to society current account',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-01T17:00:00.000Z',
    createdAt: '2026-02-01T13:30:00.000Z',
    updatedAt: '2026-02-01T17:00:00.000Z',
  },
  {
    id: 'DEP-2026-007',
    type: 'GENERAL_DEPOSIT',
    amount: 110000,
    category: 'Development Fee - Phase 1',
    date: '2026-02-05',
    shareOwnerId: 'PHSM-095',
    memberName: 'M Abu Yousuf',
    controllingDirector: 'M ABU YOUSUF',
    shareNumber: 95,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'BRAC-FT-771239',
    remarks: 'Infrastructure fund installment',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-05T19:00:00.000Z',
    createdAt: '2026-02-05T11:00:00.000Z',
    updatedAt: '2026-02-05T19:00:00.000Z',
  },
  {
    id: 'DEP-2026-008',
    type: 'GENERAL_DEPOSIT',
    amount: 110000,
    category: 'Development Fee - Phase 1',
    date: '2026-02-08',
    shareOwnerId: 'PHSM-102',
    memberName: 'Faizan Ahmed',
    controllingDirector: 'FAIZAN AHMED',
    shareNumber: 102,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'CITY-TRX-661294',
    remarks: 'Electrification line clearance',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-09T10:00:00.000Z',
    createdAt: '2026-02-08T15:00:00.000Z',
    updatedAt: '2026-02-09T10:00:00.000Z',
  },
  {
    id: 'DEP-2026-009',
    type: 'GENERAL_DEPOSIT',
    amount: 350000,
    category: '4th Unit Collective Fund',
    date: '2026-02-12',
    shareOwnerId: 'PHSM-109',
    memberName: 'Md. Rafiqul Hasan',
    controllingDirector: '4th Unit (General Reserve)',
    shareNumber: 109,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'DBBL-4TH-1192',
    remarks: '4th Unit collective share development deposit',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-13T09:30:00.000Z',
    createdAt: '2026-02-12T16:20:00.000Z',
    updatedAt: '2026-02-13T09:30:00.000Z',
  },
  // Additional Member deposits for diversity
  {
    id: 'DEP-2026-010',
    type: 'GENERAL_DEPOSIT',
    amount: 95000,
    category: 'Member Monthly Contribution',
    date: '2026-02-18',
    shareOwnerId: 'PHSM-007',
    memberName: 'Engr. Tanvir Ahmed',
    controllingDirector: 'SAIF AHMED SAKIL',
    shareNumber: 7,
    paymentMethod: 'bKash / Nagad',
    referenceNumber: 'BK-TRX-74920194',
    remarks: 'Development installment through bKash merchant',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-19T11:00:00.000Z',
    createdAt: '2026-02-18T10:15:00.000Z',
    updatedAt: '2026-02-19T11:00:00.000Z',
  },
  // Sales Deposits
  {
    id: 'DEP-2026-011',
    type: 'SALES_DEPOSIT',
    amount: 550000,
    category: 'Sales',
    date: '2026-02-20',
    salesDescription: 'Commercial Corner Plot #04 Booking Advance (Auction Sale)',
    paymentMethod: 'Pay Order',
    referenceNumber: 'PO-NBL-884920',
    remarks: 'Advance receipt for Commercial Corner Plot auction approved in AGM',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-20T16:00:00.000Z',
    createdAt: '2026-02-20T11:30:00.000Z',
    updatedAt: '2026-02-20T16:00:00.000Z',
  },
  {
    id: 'DEP-2026-012',
    type: 'SALES_DEPOSIT',
    amount: 180000,
    category: 'Sales',
    date: '2026-02-28',
    salesDescription: 'Sale of Dismantled Site Camp Scrap & Timber Trees',
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'IBBL-TRX-551029',
    remarks: 'Proceeds credited directly to Society Central Escrow Account',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'APPROVED',
    approvedBy: 'usr-del-1',
    approvedByName: 'M Masud Sawdagor',
    approvedAt: '2026-03-01T10:00:00.000Z',
    createdAt: '2026-02-28T14:40:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  // A Pending Income entry waiting for verification
  {
    id: 'DEP-2026-013',
    type: 'GENERAL_DEPOSIT',
    amount: 85000,
    category: 'Member Monthly Contribution',
    date: '2026-03-15',
    shareOwnerId: 'PHSM-025',
    memberName: 'Mohammad Ali Khan',
    controllingDirector: 'M MASUD SAWDAGOR',
    shareNumber: 25,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'EBL-TRX-993812',
    remarks: 'Awaiting bank clearance confirmation',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    status: 'PENDING',
    createdAt: '2026-03-15T09:00:00.000Z',
    updatedAt: '2026-03-15T09:00:00.000Z',
  },
];

export const INITIAL_EXPENSES: ExpenseEntry[] = [
  {
    id: 'EXP-2026-001',
    amount: 280000,
    category: 'Site Development',
    date: '2026-01-20',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    billRecipient: 'Desh Engineering & Earth Movers Ltd.',
    voucherNumber: 'VCH-2026-01',
    remarks: 'Heavy excavator earth leveling and site compaction, Sector 14',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-01-20T15:00:00.000Z',
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-01-20T15:00:00.000Z',
  },
  {
    id: 'EXP-2026-002',
    amount: 145000,
    category: 'Labor',
    date: '2026-01-28',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    billRecipient: 'Sardar Builders & Labor Syndicate',
    voucherNumber: 'VCH-2026-02',
    remarks: '30-day labor muster roll for perimeter brick wall fencing',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-01-29T11:00:00.000Z',
    createdAt: '2026-01-28T16:30:00.000Z',
    updatedAt: '2026-01-29T11:00:00.000Z',
  },
  {
    id: 'EXP-2026-003',
    amount: 95000,
    category: 'Purchase',
    date: '2026-02-03',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    billRecipient: 'Mirpur Cement & Steel Syndicate',
    voucherNumber: 'VCH-2026-03',
    remarks: '500 bags Portland Cement and 4 tons 60-grade MS Rod',
    status: 'APPROVED',
    approvedBy: 'usr-del-1',
    approvedByName: 'M Masud Sawdagor',
    approvedAt: '2026-02-04T12:00:00.000Z',
    createdAt: '2026-02-03T14:00:00.000Z',
    updatedAt: '2026-02-04T12:00:00.000Z',
  },
  {
    id: 'EXP-2026-004',
    amount: 48000,
    category: 'Electricity Bill',
    date: '2026-02-10',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    billRecipient: 'DESCO (Dhaka Electric Supply Company)',
    voucherNumber: 'VCH-2026-04',
    remarks: 'Substation high voltage construction meter bill (Jan-Feb)',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-10T17:30:00.000Z',
    createdAt: '2026-02-10T12:00:00.000Z',
    updatedAt: '2026-02-10T17:30:00.000Z',
  },
  {
    id: 'EXP-2026-005',
    amount: 35000,
    category: 'Water Bill',
    date: '2026-02-15',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    billRecipient: 'DWASA (Dhaka WASA) - Zone 9',
    voucherNumber: 'VCH-2026-05',
    remarks: 'Deep tube-well installation permit and bulk water usage fee',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-16T10:00:00.000Z',
    createdAt: '2026-02-15T15:00:00.000Z',
    updatedAt: '2026-02-16T10:00:00.000Z',
  },
  {
    id: 'EXP-2026-006',
    amount: 75000,
    category: 'Salary',
    date: '2026-02-28',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    billRecipient: 'Society Site Staff (Manager, Supervisor, 3 Guards)',
    voucherNumber: 'VCH-2026-06',
    remarks: 'February monthly payroll disbursement',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-02-28T18:00:00.000Z',
    createdAt: '2026-02-28T11:00:00.000Z',
    updatedAt: '2026-02-28T18:00:00.000Z',
  },
  {
    id: 'EXP-2026-007',
    amount: 75000,
    category: 'EC Honorarium',
    date: '2026-03-01',
    submitterId: 'usr-admin',
    submitterName: 'Saif Ahmed Sakil',
    submitterRole: 'SYSTEM_ADMIN',
    billRecipient: 'Executive Committee Members (President, GS, Treasurer)',
    voucherNumber: 'VCH-2026-07',
    remarks: 'Monthly approved honorariums as per EC resolution',
    status: 'APPROVED',
    approvedBy: 'usr-admin',
    approvedByName: 'Saif Ahmed Sakil',
    approvedAt: '2026-03-01T14:00:00.000Z',
    createdAt: '2026-03-01T09:30:00.000Z',
    updatedAt: '2026-03-01T14:00:00.000Z',
  },
  // Pending expense entry
  {
    id: 'EXP-2026-008',
    amount: 62000,
    category: 'Security',
    date: '2026-03-16',
    submitterId: 'usr-mgr-1',
    submitterName: 'Md. Rafiqul Islam (Manager)',
    submitterRole: 'MANAGER',
    billRecipient: 'Elite Force Security Services',
    voucherNumber: 'VCH-2026-08',
    remarks: 'CCTV perimeter camera installation and 2 solar streetlights',
    status: 'PENDING',
    createdAt: '2026-03-16T11:15:00.000Z',
    updatedAt: '2026-03-16T11:15:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'LOG-001',
    timestamp: '2026-01-10T10:00:00.000Z',
    userId: 'usr-admin',
    userName: 'Saif Ahmed Sakil',
    userRole: 'SYSTEM_ADMIN',
    action: 'CREATE',
    entity: 'SYSTEM_CONFIG',
    entityId: 'ROOT-INIT',
    details: 'System initialized. 144 member shares mapped to 8 Directors and 4th Unit reserve.',
  },
  {
    id: 'LOG-002',
    timestamp: '2026-01-12T14:30:00.000Z',
    userId: 'usr-admin',
    userName: 'Saif Ahmed Sakil',
    userRole: 'SYSTEM_ADMIN',
    action: 'APPROVE',
    entity: 'INCOME',
    entityId: 'DEP-2026-001',
    details: 'Approved General Deposit BDT 150,000 for member PHSM-001.',
  },
  {
    id: 'LOG-003',
    timestamp: '2026-01-20T15:00:00.000Z',
    userId: 'usr-admin',
    userName: 'Saif Ahmed Sakil',
    userRole: 'SYSTEM_ADMIN',
    action: 'APPROVE',
    entity: 'EXPENSE',
    entityId: 'EXP-2026-001',
    details: 'Approved Expense BDT 280,000 for Site Development (Desh Engineering).',
  },
  {
    id: 'LOG-004',
    timestamp: '2026-02-20T16:00:00.000Z',
    userId: 'usr-admin',
    userName: 'Saif Ahmed Sakil',
    userRole: 'SYSTEM_ADMIN',
    action: 'APPROVE',
    entity: 'INCOME',
    entityId: 'DEP-2026-011',
    details: 'Approved Sales Deposit BDT 550,000 for Commercial Corner Plot #04 Booking.',
  },
  {
    id: 'LOG-005',
    timestamp: '2026-03-01T14:00:00.000Z',
    userId: 'usr-admin',
    userName: 'Saif Ahmed Sakil',
    userRole: 'SYSTEM_ADMIN',
    action: 'APPROVE',
    entity: 'EXPENSE',
    entityId: 'EXP-2026-007',
    details: 'Disbursed monthly EC Honorarium BDT 75,000.',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'CHAT-001',
    senderId: 'usr-admin',
    senderName: 'Saif Ahmed Sakil',
    senderRole: 'SYSTEM_ADMIN',
    senderMemberId: 'PHSM-001',
    message: 'Welcome everyone to the official PHS-Finance portal! All 144 share accounts and director allocations are live and audited.',
    timestamp: '2026-02-15T10:00:00.000Z',
    category: 'EC_NOTICE',
  },
  {
    id: 'CHAT-002',
    senderId: 'usr-del-1',
    senderName: 'M Masud Sawdagor',
    senderRole: 'DELEGATED_ADMIN',
    senderMemberId: 'PHSM-021',
    message: 'Site development for Sector 14 boundary wall is progressing quickly. Please check your personal share statements for development installment balances.',
    timestamp: '2026-02-16T14:20:00.000Z',
    category: 'DEVELOPMENT_UPDATE',
  },
  {
    id: 'CHAT-003',
    senderId: 'usr-mbr-7',
    senderName: 'Engr. Tanvir Ahmed',
    senderRole: 'MEMBER',
    senderMemberId: 'PHSM-007',
    message: 'Assalamu Alaikum. Can the manager please confirm if bKash merchant fees are adjusted by the society or deducted from deposit?',
    timestamp: '2026-02-18T11:05:00.000Z',
    category: 'FINANCE_QUERY',
  },
  {
    id: 'CHAT-004',
    senderId: 'usr-mgr-1',
    senderName: 'Md. Rafiqul Islam (Manager)',
    senderRole: 'MANAGER',
    message: 'Wa Alaikum Assalam Engr. Tanvir bhai. Full deposited amount is credited directly to your member share ledger. Society absorbs transaction clearance charges.',
    timestamp: '2026-02-18T11:30:00.000Z',
    category: 'FINANCE_QUERY',
  },
];

export const INITIAL_ELECTION_POLL: ElectionPoll = {
  id: 'POLL-2026-01',
  title: '2026-2028 Executive Committee Election',
  description: 'Official voting for the next term of Prottasha Housing Society Executive Committee. Each share owner (PHSM-001 to PHSM-144) is entitled to 1 vote per registered share.',
  position: 'President',
  status: 'INACTIVE', // Inactive by default until activated by System Admin
  isActivatedByAdmin: false, // Strict Rule: No Voting Until Election Module activated by System Admin
  createdAt: '2026-03-01T00:00:00.000Z',
  closingDate: '2026-04-15T23:59:59.000Z',
  candidates: [
    {
      id: 'CAND-01',
      name: 'M Masud Sawdagor',
      memberId: 'PHSM-021',
      position: 'President',
      manifesto: 'Accelerating land registration, establishing dedicated 33kV electric substation, and complete boundary fortification by Q3 2026.',
      votes: 38,
    },
    {
      id: 'CAND-02',
      name: 'Shahin Ahmed',
      memberId: 'PHSM-056',
      position: 'President',
      manifesto: 'Transparent procurement committees, rapid handover of Phase 1 plots, and zero-interest flexible installment timeline.',
      votes: 24,
    },
    {
      id: 'CAND-03',
      name: 'Abul Hashim',
      memberId: 'PHSM-071',
      position: 'President',
      manifesto: 'High-yield society reserve investments, commercial hub leasing revenue, and immediate stormwater drainage network.',
      votes: 19,
    },
  ],
  voters: {
    'PHSM-001': 'CAND-01',
    'PHSM-002': 'CAND-01',
    'PHSM-007': 'CAND-02',
    'PHSM-021': 'CAND-01',
    'PHSM-056': 'CAND-02',
    'PHSM-071': 'CAND-03',
  },
};

export const INITIAL_DOCUMENTS: SocietyDocument[] = [
  {
    id: 'DOC-2026-001',
    title: 'Executive Committee Notice 2026/01: Phase 1 Boundary Wall & Land Demarcation Directives',
    category: 'Executive Committee Notice',
    description: 'Official EC resolution regarding boundary wall contractor mobilization, site demarcation protocols, and shareholder plot inspection schedules.',
    fileName: 'EC_Resolution_2026_01_Boundary_Wall.pdf',
    fileType: 'PDF',
    fileSize: '1.8 MB',
    uploadedBy: 'Saif Ahmed Sakil',
    uploadedByRole: 'SYSTEM_ADMIN',
    uploadedByDesignation: 'System Administrator (ISRT, DU)',
    uploadedAt: '2026-01-15T10:30:00.000Z',
    isPinned: true,
    downloadCount: 142,
  },
  {
    id: 'DOC-2026-002',
    title: 'Master Layout & Mouza Sheet Survey Map: Phase 1 & Phase 2 (144 Freehold Plots)',
    category: 'Site & Land Development',
    description: 'Certified survey engineering blueprint indicating 144 shareholder plots, 40ft central boulevard, 25ft access roads, and stormwater drainage conduits.',
    fileName: 'Prottasha_Master_Mouza_Layout_Map_2026.pdf',
    fileType: 'PDF',
    fileSize: '4.6 MB',
    uploadedBy: 'M Masud Sawdagor',
    uploadedByRole: 'DELEGATED_ADMIN',
    uploadedByDesignation: 'President & Project Director',
    uploadedAt: '2026-01-20T14:15:00.000Z',
    isPinned: true,
    downloadCount: 189,
  },
  {
    id: 'DOC-2026-003',
    title: 'Chartered Accountants Statutory Audit Report (Fiscal Year 2024-2025)',
    category: 'Financial & Audit Report',
    description: 'Unqualified independent audit opinion on central escrow bank accounts, member collections, director allocations, and site infrastructure disbursements.',
    fileName: 'Audited_Financial_Statement_FY24_25.pdf',
    fileType: 'PDF',
    fileSize: '2.9 MB',
    uploadedBy: 'Sirajul Islam',
    uploadedByRole: 'DELEGATED_ADMIN',
    uploadedByDesignation: 'Treasurer (EC)',
    uploadedAt: '2026-02-05T09:00:00.000Z',
    isPinned: false,
    downloadCount: 97,
  },
  {
    id: 'DOC-2026-004',
    title: 'Land Deed Porcha & Mutation Clearance Dossier (Khatian #1042-1088)',
    category: 'Legal & Deed Porcha',
    description: 'Certified AC Land mutation DCR, RS Porcha copies, and chain deed verification documents for society freehold acreage in Uttara Model Town extensions.',
    fileName: 'Land_Deed_Porcha_Dossier_Uttara.pdf',
    fileType: 'PDF',
    fileSize: '5.1 MB',
    uploadedBy: 'Md. Rafiqul Islam',
    uploadedByRole: 'MANAGER',
    uploadedByDesignation: 'Manager Accounts & Legal Liaison',
    uploadedAt: '2026-02-12T16:00:00.000Z',
    isPinned: false,
    downloadCount: 78,
  },
  {
    id: 'DOC-2026-005',
    title: 'Electrical Substation & Deep Tubewell Installation Blueprint (Tier-4)',
    category: 'Engineering & Layout Map',
    description: 'DESCO-approved 33kV dedicated transformer single-line diagram and deep tubewell hydrological depth technical specifications.',
    fileName: 'Substation_Tubewell_Engineering_Specs.pdf',
    fileType: 'PDF',
    fileSize: '3.4 MB',
    uploadedBy: 'Kazi Hasan',
    uploadedByRole: 'MANAGER',
    uploadedByDesignation: 'Deputy Manager (DyM)',
    uploadedAt: '2026-02-28T11:45:00.000Z',
    isPinned: false,
    downloadCount: 65,
  },
  {
    id: 'DOC-2026-006',
    title: 'Shareholder Succession & Transfer Guidelines (EC Circular 2026/04)',
    category: 'Member Circular & Guidelines',
    description: 'Standard operating procedures for nominee verification, share transfer deed execution, mutation fees, and society clearance issuance.',
    fileName: 'Share_Transfer_SOP_2026.pdf',
    fileType: 'PDF',
    fileSize: '1.2 MB',
    uploadedBy: 'Kazi Nazmul Huda',
    uploadedByRole: 'DELEGATED_ADMIN',
    uploadedByDesignation: 'General Secretary (EC)',
    uploadedAt: '2026-03-05T13:20:00.000Z',
    isPinned: false,
    downloadCount: 110,
  },
];

export const INITIAL_POSTS: DiscussionPost[] = [
  {
    id: 'POST-001',
    senderId: 'usr-hasan',
    senderName: 'Kazi Hasan',
    senderRole: 'MANAGER',
    senderDesignation: 'Deputy Manager (Field Ops)',
    message: 'Site Progress Update: Earth filling and vibro-compaction on the 40-foot central spine road is 85% completed today. Graders and heavy rollers are operational.',
    category: 'PROJECT_PROGRESS',
    timestamp: '2026-03-28T11:30:00.000Z',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?auto=format&fit=crop&w=1200&q=80',
    imageCaption: 'Heavy earth compactors levelling Sector 14 access boulevard',
    likesCount: 28,
    likedBy: ['usr-admin', 'usr-masud'],
    comments: [
      {
        id: 'COMM-001',
        userName: 'M Masud Sawdagor',
        userRole: 'DELEGATED_ADMIN',
        message: 'Excellent pace Hasan. Ensure the culvert wing walls are inspected by Thursday.',
        timestamp: '2026-03-28T12:05:00.000Z',
      },
      {
        id: 'COMM-002',
        userName: 'Engr. Tanvir Ahmed',
        userRole: 'MEMBER',
        message: 'Very reassuring to see the compaction quality. Looking forward to site inspection.',
        timestamp: '2026-03-28T14:20:00.000Z',
      },
    ],
  },
  {
    id: 'POST-002',
    senderId: 'usr-admin',
    senderName: 'Saif Ahmed Sakil',
    senderRole: 'SYSTEM_ADMIN',
    senderDesignation: 'System Administrator (DU)',
    message: 'Aerial drone survey completed for Phase 1 perimeter wall and main gate foundation pillars. All 144 shareholders can inspect high-resolution coordinates in Documentations.',
    category: 'PICTURE_SHARING',
    timestamp: '2026-03-26T15:00:00.000Z',
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
    imageCaption: 'Phase 1 boundary fortification drone aerial survey',
    likesCount: 35,
    likedBy: ['usr-admin', 'usr-masud', 'usr-hasan'],
    comments: [
      {
        id: 'COMM-003',
        userName: 'Shahin Ahmed',
        userRole: 'DELEGATED_ADMIN',
        message: 'Gate elevation looks imposing and secure. Well done team.',
        timestamp: '2026-03-26T16:45:00.000Z',
      },
    ],
  },
  {
    id: 'POST-003',
    senderId: 'usr-manager1',
    senderName: 'Md. Rafiqul Islam',
    senderRole: 'MANAGER',
    senderDesignation: 'Manager Accounts',
    message: 'Important Notice for all members: Annual share statement reconciliation is in progress. Please review your statements in "Member Ledger (144)" and use the Query Window if any adjustment is needed.',
    category: 'INFO_SHARING',
    timestamp: '2026-03-25T09:30:00.000Z',
    likesCount: 22,
    likedBy: ['usr-admin'],
    comments: [],
  },
  {
    id: 'POST-004',
    senderId: 'usr-member-002',
    senderName: 'Mohammad Ali',
    senderRole: 'MEMBER',
    senderMemberId: 'PHSM-002',
    message: 'Suggestion for the upcoming General Assembly: Could the committee consider dedicating space for an eco-friendly park and solar streetlight grid along the central reservoir?',
    category: 'GENERAL',
    timestamp: '2026-03-24T18:10:00.000Z',
    likesCount: 31,
    likedBy: ['usr-admin', 'usr-masud'],
    comments: [
      {
        id: 'COMM-004',
        userName: 'Kazi Nazmul Huda',
        userRole: 'DELEGATED_ADMIN',
        message: 'This is already included in Tier-4 utility planning. Will present detailed 3D renders at AGM.',
        timestamp: '2026-03-24T19:30:00.000Z',
      },
    ],
  },
];

export const INITIAL_QUERIES: MemberQuery[] = [
  {
    id: 'QRY-2026-001',
    memberId: 'PHSM-014',
    shareNumber: 14,
    submitterName: 'Dr. Mahmudur Rahman',
    submitterPhone: '+8801711223344',
    category: 'Finance & Deposit Query',
    subject: 'Verification of DBBL Cheque Deposit for Phase 1 Development Share',
    referenceId: 'DEP-2026-002',
    details: 'I deposited a clearing cheque of ৳180,000 on Jan 14th via manager Md. Rafiqul. Could accounts please verify that this transaction is marked Approved on my member statement?',
    status: 'RESOLVED',
    submittedAt: '2026-01-16T10:00:00.000Z',
    assignedTo: 'Md. Rafiqul Islam (Manager Accounts)',
    resolvedAt: '2026-01-16T15:30:00.000Z',
    resolvedBy: 'Md. Rafiqul Islam',
    resolutionRemarks: 'Deposit verified through DBBL Uttara branch clearing. Approved as DEP-2026-002 in official ledger.',
    responses: [
      {
        id: 'RESP-001',
        responderName: 'Md. Rafiqul Islam',
        responderRole: 'MANAGER',
        responderDesignation: 'Manager Accounts',
        message: 'Dear Dr. Mahmudur, your DBBL clearing transaction of ৳180,000 was verified and approved on Jan 15th. It is reflected in your Member Statement with voucher reference DEP-2026-002. Thank you for your prompt installment.',
        respondedAt: '2026-01-16T15:30:00.000Z',
      },
    ],
  },
  {
    id: 'QRY-2026-002',
    memberId: 'PHSM-045',
    shareNumber: 45,
    submitterName: 'Engr. Tanvir Ahmed',
    submitterPhone: '+8801811556677',
    category: 'Site & Land Development',
    subject: 'Final sand filling elevation relative to 40ft central road',
    referenceId: 'Plot-B45',
    details: 'Could the project engineers confirm what the finished floor level guideline is for Plot 45? We want to ensure proper drainage slope into the concrete box culvert.',
    status: 'IN_REVIEW',
    submittedAt: '2026-02-10T11:20:00.000Z',
    assignedTo: 'Kazi Hasan (DyM Field Ops)',
    responses: [
      {
        id: 'RESP-002',
        responderName: 'Kazi Hasan',
        responderRole: 'MANAGER',
        responderDesignation: 'Deputy Manager (Field Ops)',
        message: 'Assigned to site engineering desk. Finished road elevation is set at +2.8ft above maximum 50-year flood benchmark, with a 1:100 lateral gradient toward the southern storm conduit. Detailed cross-section drawing attached in Documentations.',
        respondedAt: '2026-02-11T09:40:00.000Z',
      },
    ],
  },
  {
    id: 'QRY-2026-003',
    memberId: 'PHSM-088',
    shareNumber: 88,
    submitterName: 'Sirajul Islam',
    submitterPhone: '+8801711667788',
    category: 'Share Transfer & Ownership',
    subject: 'Nominee registration form submission for co-shareholder',
    details: 'Can I upload the nominee NID and passport-size photograph directly through the User Profile portal or is physical submission required at the registered society office?',
    status: 'OPEN',
    submittedAt: '2026-03-20T14:00:00.000Z',
    responses: [],
  },
];

